engines:
  rubocop:
    enabled: true
  brakeman:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 60
ratings:
  paths:
    - lib/**
    - "**.rb"
exclude_paths:
  - spec/**/*
